apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: go-kubernetes-api
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-kubernetes-frontend
            port:
              number: 80      
